version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root        
      MYSQL_DATABASE: karan                
      MYSQL_USER: user                         
      MYSQL_PASSWORD: password             
    volumes:
      - d:/mysql-data:/var/lib/mysql           

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db                             
      PMA_USER: user                           
      PMA_PASSWORD: password               
      MYSQL_ROOT_PASSWORD: root        

volumes:
  db-data:
