version: '3.9'
volumes:
  web_source:
  db_source:


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - web_source:/home/dev/source
    restart: on-failure
    command: [ "sleep", "infinity" ]

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: activitydb
    volumes:
      - db_source:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: activitydb
